// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlrXfQSVOyEf35ixnQhhd5i3x_AcGrKnA',
    appId: '1:962064009792:web:43948990f1294570a16da5',
    messagingSenderId: '962064009792',
    projectId: 'quanlyhoctap-a05de',
    authDomain: 'quanlyhoctap-a05de.firebaseapp.com',
    storageBucket: 'quanlyhoctap-a05de.firebasestorage.app',
    measurementId: 'G-R2B15KDDT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQ6QDBy8Hw2TflvVoJdvSANPn06tnVKQ',
    appId: '1:962064009792:android:6b34efba64b486fca16da5',
    messagingSenderId: '962064009792',
    projectId: 'quanlyhoctap-a05de',
    storageBucket: 'quanlyhoctap-a05de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLPZsa2TMqpRNoTthHKaWVf6vEgaNo9qo',
    appId: '1:962064009792:ios:a6a6b90597fb4511a16da5',
    messagingSenderId: '962064009792',
    projectId: 'quanlyhoctap-a05de',
    storageBucket: 'quanlyhoctap-a05de.firebasestorage.app',
    iosBundleId: 'com.example.quanLyHocTap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLPZsa2TMqpRNoTthHKaWVf6vEgaNo9qo',
    appId: '1:962064009792:ios:a6a6b90597fb4511a16da5',
    messagingSenderId: '962064009792',
    projectId: 'quanlyhoctap-a05de',
    storageBucket: 'quanlyhoctap-a05de.firebasestorage.app',
    iosBundleId: 'com.example.quanLyHocTap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlrXfQSVOyEf35ixnQhhd5i3x_AcGrKnA',
    appId: '1:962064009792:web:012cb592c037dcb8a16da5',
    messagingSenderId: '962064009792',
    projectId: 'quanlyhoctap-a05de',
    authDomain: 'quanlyhoctap-a05de.firebaseapp.com',
    storageBucket: 'quanlyhoctap-a05de.firebasestorage.app',
    measurementId: 'G-T98F6723E6',
  );
}
